baseurl: "https://mathpol.github.io/bost/"
title: BOST Blog
theme: hugo-theme-cleanwhite
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
preserveTaxonomyNames: yes
paginate: 5
hasCJKLanguage: yes
outputs:
  home:
    - HTML
    - RSS
    - Algolia
params:
  SEOTitle: BOST
  about_me: no
  addtional_menus:
    - href: /top/sobre/
      title: SOBRE
    - href: /top/documentos/
      title: Documentos
    - href: /top/inscricao/
      title: Inscrição
    - href: /top/programacao/
      title: Programação      
    - href: /top/pessoas/
      title: Pessoas
  algolia:
    params:
      - categories
      - tags
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
  algolia_apiKey: ''
  algolia_appId: ''
  algolia_indexName: ''
  algolia_search: yes
  ba_track_id: ''
  bookmark_link:
    - href: https://martinfowler.com
      title: Martin Fowler
    - href: http://www.servicemesher.com
      title: ServiceMesher
    - href: https://pxhere.com
      title: Pxhere
    - href: https://unsplash.com
      title: unsplash
  bookmarks: no
  description: DESCRIPTION
  disqus_proxy: ''
  disqus_site: ''
  featured_condition_size: 1
  featured_tags: no
  header_image: "img/tag-bg.jpg"
  image_404: img/404-bg.jpg
  keyword: 
  leancloud_app_id: ''
  leancloud_app_key: ''
  omit_categories: no
  page_view_conter: no
  reward: no
  slogan: 
  social:
    email: 
    github: 
    linkedin: 
    rss: no
    wechat: 
  title_404: 
  twikoo_env_id: ''
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: yes
    mediaType: application/json
    notAlternative: yes
markup:
  highlight:
    style: dracula
  tableOfContents:
    endLevel: 2
    startLevel: 1