---
title: "Brazilian Open Science Training (BOST)"
author: "Matheus"
date: 2022-02-22
tags: ["BITSS", "RT2", "Transparency", "Social Science"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Brazilian Open Science Training (BOST)

Brazilian Open Science Training (BOST) surge com o objetivo de apresentar princípios e práticas de pesquisa aberta e transparente, em língua portuguesa, inspirados no Treinamento em Tansparência e Reprodutibilidade (RT2) oferecido pela Berkeley Initiative in the Social Science (BITSS). Durante o curso, as (os) participantes terão  a oportunidade de aprender os princípios e habilidades necessários para produção do conhecimento científico que atendem os padrões internacionais para uma pesquisa de qualidade e confiável.

Organizado por discentes e professores da UFPE e UFMG, o treinamento tem o apoio do CEGA/BITSS e promoverá a  formação de estudantes de pós-graduação durante 4 dias, aprofundando em temas como i) princípios da transparência e reprodutibilidade nas Ciências Sociais; ii) documentos dinâmicos em RMarkdown; iii) versionamento de arquivos em Git e Github com R Studio; iv) pré-registro e plano de pré-análise (pre-registration and pre-analysis plan); v) Open Science Framework; vi) passo a passo para tornar sua pesquisa transparente e reprodutível; e vii) transparência e replicabilidade fora da academia.


**Datas importantes:**

*	04/03/2022 – Abertura das inscrições

*	04/04/2022 – Encerramento das inscrições

*	21/04/2022 – Notificação dos participantes selecionados

*	19/05/2022 – Primeiro dia de evento


# Clique aqui para baixar o edital

[Download Edital](https://drive.google.com/file/d/1AajuNpTlUaVQ_eD18thimHQiCuNooonU/view?usp=sharing)

# Link para inscrição


Clique [aqui](https://docs.google.com/forms/d/1_TNHPAkoEejj-My7uS-jkkk4q18hvBCnh7jLk_gIYAA/edit) para se inscrever no evento.
